### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by mihabozic123** [FGRibreau/node-unidecode#25]
Full error:
C:\Users\Miha\MBot\node_modules\unidecode\unidecode.js:20
  return str.replace(utf8_rx, unidecode_internal_replace);
             ^

TypeError: Cannot read property 'replace' of undefined
    at module.exports (C:\Users\Miha\MBot\node_modules\←[4munidecode←[24m\unidecode.js:20:14)
    at module.exports (C:\Users\Miha\MBot\handlers\responses.js:14:26)
    at C:\Users\Miha\MBot\index.js:27:85
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\Miha\MBot\index.js:27:46)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)←[39m

code part:
const cleanmsg = unidecode(message.content).toLowerCase().replace(/0/g,"o");

**Comment by FGRibreau** [comment]
Not enough data to understand what is going on. Closing.
