### ISSUE TITLE
Feature Request: Transliterate Unicode "Fonts"

### ISSUE THREAD

**Issue by jhuckaby** [FGRibreau/node-unidecode#26]
Using special Unicode glyphs, people can produce custom "fonts" such as:

- 𝐍𝐨𝐰 𝐢𝐬 𝐭𝐡𝐞 𝐭𝐢𝐦𝐞 𝐟𝐨𝐫 𝐚𝐥𝐥 𝐠𝐨𝐨𝐝 𝐦𝐞𝐧.
- 𝓝𝓸𝔀 𝓲𝓼 𝓽𝓱𝓮 𝓽𝓲𝓶𝓮 𝓯𝓸𝓻 𝓪𝓵𝓵 𝓰𝓸𝓸𝓭 𝓶𝓮𝓷.
- ℕ𝕠𝕨 𝕚𝕤 𝕥𝕙𝕖 𝕥𝕚𝕞𝕖 𝕗𝕠𝕣 𝕒𝕝𝕝 𝕘𝕠𝕠𝕕 𝕞𝕖𝕟.
- 𝙽𝚘𝚠 𝚒𝚜 𝚝𝚑𝚎 𝚝𝚒𝚖𝚎 𝚏𝚘𝚛 𝚊𝚕𝚕 𝚐𝚘𝚘𝚍 𝚖𝚎𝚗.

Source: http://qaz.wtf/u/convert.cgi?text=Now+is+the+time+for+all+good+men.

This is becoming wildly popular in recent years.  It would be wonderful if unidecode could transliterate these back to ASCII.  Desire:

```js
const unidecode = require('unidecode');
console.log( unidecode("𝓝𝓸𝔀 𝓲𝓼 𝓽𝓱𝓮 𝓽𝓲𝓶𝓮 𝓯𝓸𝓻 𝓪𝓵𝓵 𝓰𝓸𝓸𝓭 𝓶𝓮𝓷.") );
// Desired Output: Now is the time for all good men.
```

Much thanks!

**Comment by FGRibreau** [comment]
Hello @jhuckaby!

Great idea! I'm open to accept a pull request in that direction :+1:

**Comment by FGRibreau** [comment]
We are not a full mirror of perl project Text::unicode https://metacpan.org/release/SBURKE/Text-Unidecode-0.04/view/lib/Text/Unidecode.pm please report this issue there and we will propagate the change here :)
