### ISSUE TITLE
Support Custom Substitution

### ISSUE THREAD

**Issue by amagid** [FGRibreau/node-unidecode#27]
Hi @FGRibreau!

First of all, I love this module and use it extensively - so thank you for putting it together!

I'm working with some legacy systems that are very picky about the length of strings, and the problem I'm having with this module is that untranslatable characters are stripped out from the string, which changes the length and makes it invalid for the legacy systems I work with.

What I'd like to be able to do is supply a custom substitution value to use when no valid translation is found, for example a space character or an underscore. If I could do that, the length would be maintained and I'd be able to use this module for my projects again.

I'll submit a PR in a minute for the change so you can take a look.

**Comment by FGRibreau** [comment]
I've looked at the code:
- i'm ok with the whole idea
- could you please also update the test suite (add some new tests that match your requirements)?
- please also update README.md with this advanced usage

**Comment by amagid** [comment]
Great. I added test cases and updated the README.

Should I update the changelog or will you do that?

**Comment by FGRibreau** [comment]
Released in v1.0.0
