### ISSUE TITLE
Greek translit

### ISSUE THREAD

**Issue by retorquere** [FGRibreau/node-unidecode#32]
When transliterating `Ξανθοπούλου`, unidecode produces `Ksanthopoulou` which should [apparently](https://github.com/retorquere/zotero-better-bibtex/issues/2975) be `Xanthopoulou`. That issue also names a few more potential problem spots for greek translit.

**Comment by FGRibreau** [comment]
I will happily accept a PR with updated tests for that :)

**Comment by retorquere** [comment]
I understand that, and I will see if the user reporting the issue has interest in doing that. My plate is already overflowing, I can't take this on.

**Comment by Jmuccigr** [comment]
@FGRibreau, I'm the OP on that issue. Let me look at the files.

**Comment by Jmuccigr** [comment]
OK, done. #33

**Comment by FGRibreau** [comment]
Hum, indeed the current tests pass, but next time I use ./scripts/update-files.sh your changes will be removed because these changes must be done upstream on https://metacpan.org/release/SBURKE/Text-Unidecode-0.04/view/lib/Text/Unidecode.pm please do your change there and then I will propage them here :)

**Comment by Jmuccigr** [comment]
Ah, I didn't know that. And I'm not sure how to do a PR over there, so I've emailed that developer. Will update.

**Comment by FGRibreau** [comment]
Thanks a lot @Jmuccigr, I've added a [CONTRIBUTING.md](./CONTRIBUTING.md) file to prevent further issues with other devs that would like to update node-unidecode :)

**Comment by Jmuccigr** [comment]
Checking in after a long while. The dev never replied to me and now the cpan email listed there doesn't work. Just FYI.
